# Generated by Django 4.0.2 on 2022-02-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0002_bank_bankcard_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='pub_date',
        ),
    ]
