# Generated by Django 4.0.2 on 2022-02-19 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0003_remove_bank_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankcard',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.IntegerField(unique=True),
        ),
    ]
