# Generated by Django 4.0.2 on 2022-02-19 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0004_bank_create_time_bankcard_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 12, 39, 16, 180633, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 12, 39, 16, 180633, tzinfo=utc), null=True),
        ),
    ]
